name: Facebook Live Stream

on:
  schedule:
    # تحديد الوقت الذي ستعمل فيه العملية. هذا المثال يعمل كل 5 دقائق.
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  stream_facebook:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Start Facebook Live Stream
      run: |
        python -c "
import subprocess

# إعداد الـ Cookies التي تحصل عليها من فيسبوك
cookies = {
    'datr': 'dSdBZ8ZGxPbQR8tNY23cgN_J',
    'sb': 'dSdBZ3uKi5P7y8smUuJjarYd',
    'ps_l': '1',
    'ps_n': '1',
    'wd': '431x809',
    'c_user': '61557829686505',
    'fr': '0nWlCq3pL1pOqh3ei.AWWdKhbVMMcrfFrP_TBldgmms6E.BnQSd1..AAA.0.0.BnQSed.AWW97AQd4nU',
    'xs': '37%3Ats7aR5f3BgV-kA%3A2%3A1732323231%3A-1%3A6995',
    'locale': 'fr_FR',
    'wl_cbv': 'v2%3Bclient_version%3A2679%3Btimestamp%3A1732323238',
    'fbl_st': '100727379%3BT%3A28872054',
    'vpd': 'v1%3B809x431x2.5062501430511475'
}

# URL الخاص بالبث
m3u8_url = 'https://live4.beinconnect.us/YallaGoalApp/beINSports1.m3u8'
stream_key = 'FB-122166221492260989-0-AbyDiyB_Nr94DEcp'

# إعداد الأمر الخاص بـ FFmpeg للبث
ffmpeg_command = [
    'ffmpeg',
    '-i', m3u8_url,  # رابط الفيديو
    '-c:v', 'libx264',  # الترميز
    '-preset', 'fast',
    '-max_muxing_queue_size', '1024',
    '-f', 'flv',  # التنسيق
    f'rtmps://live-api-s.facebook.com:443/rtmp/{stream_key}'  # رابط البث مع الـ Stream Key
]

# تشغيل البث باستخدام FFmpeg
subprocess.run(ffmpeg_command)
"
